format = '$os$all'
palette = "gruvbox_material_dark"

[username]
show_always = false
format = "[$user]($style)"

[os]
disabled = false
format = '[$symbol](gruv_blue)'

[character]
success_symbol = "[](gruv_green)"
error_symbol = "[](gruv_red)"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = "  "

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
symbol = " "

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
symbol = " "

[crystal]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = " "

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = " "

[elm]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[gradle]
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'
symbol = " "

[haskell]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[haxe]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[julia]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[kotlin]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = "󰍛 "

[meson]
format = '\[[$symbol$project]($style)\]'
symbol = "󰔷 "

[nim]
format = '\[[$symbol($version)]($style)\]'
symbol = "󰆥 "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
symbol = " "

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
symbol = " "

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'
symbol = "󰏗 "

[perl]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[php]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'
symbol = " "

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = " "

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "󱘗 "

[rlang]
symbol = "󰟔 "

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[solidity]
format = '\[[$symbol($version)]($style)\]'

[buf]
symbol = " "

[directory]
truncation_length = 8
truncation_symbol = '…/'
format = ' [$path ]($style)[$read_only]($read_only_style)'
read_only = " 󰌾"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[palettes.catppuccin_mocha]
cat_rosewater = "#f5e0dc"
cat_flamingo = "#f2cdcd"
cat_pink = "#f5c2e7"
cat_mauve = "#cba6f7"
cat_red = "#f38ba8"
cat_maroon = "#eba0ac"
cat_peach = "#fab387"
cat_yellow = "#f9e2af"
cat_green = "#a6e3a1"
cat_teal = "#94e2d5"
cat_sky = "#89dceb"
cat_sapphire = "#74c7ec"
cat_blue = "#89b4fa"
cat_lavender = "#b4befe"
cat_text = "#cdd6f4"
cat_subtext1 = "#bac2de"
cat_subtext0 = "#a6adc8"
cat_overlay2 = "#9399b2"
cat_overlay1 = "#7f849c"
cat_overlay0 = "#6c7086"
cat_surface2 = "#585b70"
cat_surface1 = "#45475a"
cat_surface0 = "#313244"
cat_base = "#1e1e2e"
cat_mantle = "#181825"
cat_crust = "#11111b"

[palettes.gruvbox_material_dark]
gruv_fg0 = '#d4be98'
gruv_bg1 = '#32302f'
gruv_bg3 = '#45403d'
gruv_blue = '#7daea3'
gruv_aqua = '#89b482'
gruv_green = '#a9b665'
gruv_orange = '#e78a4e'
gruv_purple = '#d3869b'
gruv_red = '#ea6962'
gruv_yellow = '#d8a657'
