$fg = rgb(d4be98)
$bg = rgb(282828)

$fg0 = rgb(d4be98)
$fg2 = rgb(a89984)
$fg3 = rgb(928374)
$fg4 = rgb(7c6f64)

$bg_h = rgb(1b1b1b)
$bg_s = rgb(32302f)
$bg1 = rgb(32302f)
$bg2 = rgb(32302f)
$bg3 = rgb(45403d)
$bg4 = rgb(5a524c)

$red = rgb(ea6962)
$green = rgb(a9b665)
$yellow = rgb(d8a657)
$blue = rgb(7daea3)
$purple = rgb(d3869b)
$aqua = rgb(89b482)
$orange = rgb(e78a4e)

$grey_light = rgb(a89984)
$grey_dark = rgb(928374)
