$fg0 = rgb(d4be98)
$fg1 = rgb(ddc7a1)
$fg2 = rgb(a89984)
$fg3 = rgb(928374)
$fg4 = rgb(7c6f64)

$bg0     = rgb(282828)
$bg_dim  = rgb(1b1b1b)
$bg_soft = rgb(32302f)
$bg_med  = rgb(45403d)
$bg_hard = rgb(5a524c)

$red    = rgb(ea6962)
$green  = rgb(a9b665)
$yellow = rgb(d8a657)
$blue   = rgb(7daea3)
$purple = rgb(d3869b)
$aqua   = rgb(89b482)
$orange = rgb(e78a4e)

$grey_light = rgb(a89984)
$grey_dark  = rgb(928374)
