# Gruvbox Material Dark Medium
include themes/gruvbox-material.conf

font_family                 JetBrainsMono Nerd Font
font_size 	            	12.0
window_padding_width 	    4
background_opacity          0.8

cursor_shape 				block
shell_integration 			no-cursor

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

map ctrl+shift+page_up   no_op
map ctrl+shift+page_down no_op

map ctrl+page_up scroll_page_down
map ctrl+page_down scroll_page_up

map ctrl+shift+page_up   change_font_size all +1.0
map ctrl+shift+page_down change_font_size all -1.0
